baseURL = "http://omen-.github.io/"
languageCode = "en-us"
title = "Arthur Bellal"
author = "Arthur Bellal"
pygmentsuseclasses = true
theme = "cocoa"
googleAnalytics = "UA-108126571-1"
pygmentsCodeFences = true

[params]
  latestpostscount = 3
  github = "//github.com/omen-"
  linkedin = "//linkedin.com/in/arthur-bellal"
  email = "arthur@bell.al"
  angel = "//angel.co/arthur-bellal"
  author = "Arthur Bellal"

[[menu.main]]
  name = "Resume"
  weight = 3
  url = "/resume.pdf"

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "Blog"
weight                 = -120
identifier             = "blog"
url = "/blog/"