baseURL = "http://omen-.github.io/"
languageCode = "en-us"
title = "Arthur Bellal"
theme = "hyde"
googleAnalytics = "UA-108126571-1"

[params]
  description = "Stories on how I construct or break stuff"

[[menu.main]]
  name = "Resume"
  weight = 3
  url = "/resume.pdf"